[package]
name = "editor-carrosseis-desktop"
version = "0.1.5"
description = "Editor de Carrosseis"
authors = ["Matheus De Lucca"]
edition = "2021"
rust-version = "1.77"
build = "build.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
